#!/usr/bin/env bash

set -euo pipefail

##? Setups the environment
#?? 1.0.0
##?
##? Usage:
##?    install

echo "🚀 Welcome to the Neovim config installer!"
echo "-------------------------------------------------"
echo

echo "👉  Cloning NVChad "
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1

echo "👉  Cloning jvegaf custom config "
gh repo clone nvchad_custom ~/.config/nvim/lua/custom

echo "Installing ..."

nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

echo "Neovim config done "